// TAPIEventNotification.h: interface for the CTAPIEventNotification class.
//
//////////////////////////////////////////////////////////////////////

#if !defined(AFX_TAPIEVENTNOTIFICATION_H__7A3B39A9_8188_4063_B4CD_64F4B88C2864__INCLUDED_)
#define AFX_TAPIEVENTNOTIFICATION_H__7A3B39A9_8188_4063_B4CD_64F4B88C2864__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

#include "tapi3.h"

#endif // !defined(AFX_TAPIEVENTNOTIFICATION_H__7A3B39A9_8188_4063_B4CD_64F4B88C2864__INCLUDED_)
/////////////////////////////////////////////////////////////////////////////

//This Class is the event sink for the call notifications generated by tapi on call recieval////////


class CTAPIEventNotification : public ITTAPIEventNotification
{
public:
	CTAPIEventNotification();
	UINT WM_PRIVATETAPIEVENT;
	long m_cRef;
	HRESULT STDMETHODCALLTYPE Event(TAPI_EVENT  TapiEvent,IDispatch *pEvent);
	ULONG STDMETHODCALLTYPE AddRef();
	ULONG STDMETHODCALLTYPE Release();
	HRESULT STDMETHODCALLTYPE QueryInterface(REFIID iid,void **ppv);


};
